name: hugo

services:
    main:
        image: klakegg/hugo:ext-alpine
        command: server -D --disableFastRender
        volumes:
            - .:/src:z
        ports:
            - 1313:1313
    nginx:
        image: nginx
        volumes:
            - ./public:/usr/share/nginx/html:z
        ports:
            - 8080:80

